/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author SENA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JDesktopPane();
        menus = new javax.swing.JMenuBar();
        Menu_A = new javax.swing.JMenu();
        Reg_asistencia = new javax.swing.JMenuItem();
        Menuregistrosusuarios = new javax.swing.JMenu();
        MItemregistros = new javax.swing.JMenuItem();
        MenuItemtabla_reg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        Panel.setBackground(new java.awt.Color(102, 255, 204));
        Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        Menu_A.setText("Asistencias");
        Menu_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Reg_asistencia.setText("Reg.Asistencia");
        Reg_asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_A.add(Reg_asistencia);

        menus.add(Menu_A);

        Menuregistrosusuarios.setText("Registros");
        Menuregistrosusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MItemregistros.setText("Registros");
        MItemregistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menuregistrosusuarios.add(MItemregistros);

        MenuItemtabla_reg.setText("Tabla_Registros");
        MenuItemtabla_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemtabla_regActionPerformed(evt);
            }
        });
        Menuregistrosusuarios.add(MenuItemtabla_reg);

        menus.add(Menuregistrosusuarios);

        setJMenuBar(menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemtabla_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemtabla_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemtabla_regActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem MItemregistros;
    public javax.swing.JMenuItem MenuItemtabla_reg;
    public javax.swing.JMenu Menu_A;
    public javax.swing.JMenu Menuregistrosusuarios;
    public javax.swing.JDesktopPane Panel;
    public javax.swing.JMenuItem Reg_asistencia;
    public javax.swing.JMenuBar menus;
    // End of variables declaration//GEN-END:variables

}
