/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Gonzalo01
 */
public class Reporte_Asistencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reporte_Asistencia
     */
    public Reporte_Asistencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Id_Title = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btn_Entrada = new javax.swing.JButton();
        Btn_Salida = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        Nom_Title5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        Apellido1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        LblAmPm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setForeground(java.awt.Color.black);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reporte");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Titulo.setText("Registro De Entrada Y Salida");

        Id_Title.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Id_Title.setText("Identificacion");

        Apellido.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Apellido.setText("Rol");

        txtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtRol.setEditable(false);
        txtRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setText("INSTITUCION EDUCATIVA LA AGUADA SEDE PRINCIPAL");

        Btn_Entrada.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Btn_Entrada.setBorderPainted(false);
        Btn_Entrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EntradaActionPerformed(evt);
            }
        });

        Btn_Salida.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Btn_Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalidaActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        date.setText("YY/MM/DD");

        hour.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        hour.setText("00:00:00");

        Nom_Title5.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Nom_Title5.setText("Nombres");

        txtNombres.setEditable(false);
        txtNombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Apellido1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Apellido1.setText("Apellidos");

        txtApellidos.setEditable(false);
        txtApellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LblAmPm.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        LblAmPm.setText("ap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Id_Title)
                            .addComponent(Nom_Title5)
                            .addComponent(Apellido1)
                            .addComponent(Apellido))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Btn_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(Btn_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(date)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(hour)
                    .addComponent(LblAmPm))
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id_Title)
                        .addGap(30, 30, 30)
                        .addComponent(Nom_Title5)
                        .addGap(30, 30, 30)
                        .addComponent(Apellido1)
                        .addGap(30, 30, 30)
                        .addComponent(Apellido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EntradaActionPerformed

    private void Btn_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Apellido;
    public javax.swing.JLabel Apellido1;
    public javax.swing.JButton Btn_Entrada;
    public javax.swing.JButton Btn_Salida;
    public javax.swing.JLabel Id_Title;
    public javax.swing.JLabel LblAmPm;
    public javax.swing.JLabel Nom_Title5;
    public javax.swing.JLabel Titulo;
    public javax.swing.JLabel date;
    public javax.swing.JLabel hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
